{{- $releaseRevision := include "jboss-wildfly.releaseRevision" . }}

{{- if .Values.bluegreen.enabled -}}
{{ else }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "jboss-wildfly.fullname" . }}
  labels:
    {{- include "jboss-wildfly.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "jboss-wildfly.selectorLabels" . | nindent 6 }}
  minReadySeconds: {{ .Values.minReadySeconds }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "jboss-wildfly.selectorLabels" . | nindent 8 }}
    spec:
      imagePullSecrets:
        - name: {{ template "jboss-wildfly.fullname" . }}-imagepullsecret
      serviceAccountName: {{ include "jboss-wildfly.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if or .Values.configMap.enabled .Values.secretsmanager.enabled }}
          volumeMounts:
          {{- if .Values.configMap.enabled }}
          - name: config
            mountPath: "/config"
            readOnly: true
          {{- end }}
          {{- if .Values.secretsmanager.enabled }}
          - name: {{ include "jboss-wildfly.fullname" . }}-{{ $releaseRevision }}
            mountPath: "/mnt/secrets-store"
            readOnly: true
          {{- end }} 
          {{- end }}
          env:
            - name: context_path
              value: {{ .Values.container.path }}
            - name: container_port
              value: "{{ .Values.container.port }}"
            {{- range $key, $val := .Values.env.normal }}
            - name: {{ $key }}
              value: {{ $val | quote}}
            {{- end }}
            {{- if .Values.secretsmanager.enabled }}
            {{- range $key, $val := .Values.env.secret }}
            {{- range $val.key }}
            - name: {{ . }}
              valueFrom:
                secretKeyRef:
                  name: {{ $key }}-{{ $releaseRevision }}
                  key: {{ . }}
            {{- end }}
            {{- end }}
            {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.container.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: {{ .Values.container.path }}
              port: http
          readinessProbe:
            httpGet:
              path: {{ .Values.container.path }}
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- if or .Values.configMap.enabled .Values.configMap.enabled }}
      volumes:
      {{- if .Values.configMap.enabled }}
      - name: config
        configMap:
          name: {{ template "jboss-wildfly.fullname" . }}-config
      {{- end }}
      {{- if .Values.secretsmanager.enabled }}
      - name: {{ include "jboss-wildfly.fullname" . }}-{{ $releaseRevision }}
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: {{ include "jboss-wildfly.fullname" . }}-{{ $releaseRevision }} # Name of the secretProviderClass
      {{- end }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
