
{{- if .Values.bluegreen.enabled -}}
{{ else }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "mmkubeapps.fullname" . }}
  labels:
    {{- include "mmkubeapps.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "mmkubeapps.selectorLabels" . | nindent 4 }}
{{- end }}
