{{- $releaseRevision := include "cmdexe-mmkubeapps.releaseRevision" . }}
{{- if .Values.secretsmanager.enabled }}
apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: {{ include "cmdexe-mmkubeapps.fullname" . }}-{{ $releaseRevision }}
  labels:
    {{- include "cmdexe-mmkubeapps.labels" . | nindent 4 }}
spec:
  provider: aws
  secretObjects:
    {{- range $key, $val := .Values.env.secret }}  
    - secretName: {{ $key }}-{{ $releaseRevision }}
      type: Opaque
      labels:
        {{- include "cmdexe-mmkubeapps.secretsManagerLabels" $ | nindent 8 }}
      data:
        {{- range $val.key }}
        - objectName: "{{ . }}alias"
          key: {{ . }}
        {{- end }}
        {{- end }}
  parameters:
    objects: |
      {{- range $key, $val := .Values.env.secret }}
      - objectName: {{ $key }}
        objectType: "secretsmanager"
        jmesPath:
          {{- range $val.key }}
          - path: '"{{ . }}"'
            objectAlias: "{{ . }}alias"
          {{- end }}
      {{- end }}
{{- end }}