{{- if .Values.bluegreen.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "cmdexe-mmkubeapps.fullname" . }}-service-prod
  labels:
    {{- include "cmdexe-mmkubeapps.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
 {{- include "cmdexe-mmkubeapps.selectorLabels" . | nindent 4 }}
    slot: {{ .Values.productionSlot }}
{{- end }}
