{{- if .Values.bluegreen.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "java-spring-boot.fullname" . }}-service-stage
  labels:
    {{- include "java-spring-boot.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "java-spring-boot.labels" . | nindent 4 }}
    {{- if eq .Values.productionSlot "blue" }}
    slot: green
    {{- else }}
    slot: blue
    {{- end }}
{{- end }}
